version: "3"
services:
  postgres:
    container_name: nestjs-discussion-postgres
    image: postgres:12-bullseye
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres
  pgadmin:
    links:
    - postgres:postgres
    container_name: nestjs-discussion-pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
  redis:
    image: redis:latest
    container_name: nestjs-discussion-redis-container
    volumes:
    - ./data/redis-data:/data
    privileged: true
    ports:
      - "6380:6379" # Map container's Redis port to host machine's port
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
  #   container_name: kibana
  #   volumes:
  #     - kibana-data:/usr/share/kibana/data
  #   ports:
  #    - ${KIBANA_PORT}:5601
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nestjs-discussion-redis-commander
    environment:
      - REDIS_PORT=6379 # The host and port of your Redis server
      - REDIS_HOST=redis # The host and port of your Redis server
    ports:
      - "8081:8081" # Map container's Redis Commander port to host machine's port
    depends_on:
      - redis
networks:
  postgres:
    driver: bridge
volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
