export class EnvironmentConstants {
  static NODE_ENV = 'NODE_ENV';
  static POSTGRES_HOST = 'POSTGRES_HOST';
  static POSTGRES_PORT = 'POSTGRES_PORT';
  static POSTGRES_USER = 'POSTGRES_USER';
  static POSTGRES_PASSWORD = 'POSTGRES_PASSWORD';
  static POSTGRES_DB = 'POSTGRES_DB';
  static PORT = 'PORT';
  static SYNCHONRIZE = 'SYNCHONRIZE';
  static JWT_SECRET = 'JWT_SECRET';
  static JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN';
  static REDIS_HOST = 'REDIS_HOST';
  static REDIS_PORT = 'REDIS_PORT';
  static USER_TOKEN_CACHE_KEY = 'USER_TOKEN_CACHE_KEY';
  static COOKIE_JWT_ACCESS_TOKEN_KEY = 'COOKIE_JWT_ACCESS_TOKEN_KEY';
  static COOKIE_REFRESH_TOKEN_KEY = 'COOKIE_REFRESH_TOKEN_KEY';
  static JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
  static JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN';
  static PASSWORD_RESET_TOKEN_SECRET = 'PASSWORD_RESET_TOKEN_SECRET';
  static PASSWORD_RESET_TOKEN_EXPIRES_IN = 'PASSWORD_RESET_TOKEN_EXPIRES_IN';
  static FRONTNED_URL = 'FRONTNED_URL';
  static EMAIL_VERIFICATION_TOKEN_SECRET = 'EMAIL_VERIFICATION_TOKEN_SECRET';
  static EMAIL_VERIFICATION_TOKEN_EXPIRES_IN =
    'EMAIL_VERIFICATION_TOKEN_EXPIRES_IN';
}
